// Generated by CoffeeScript 1.9.3
(function() {
  var audio, request, url;

  try {
    audio = new AudioContext();
  } catch (_error) {}

  url = 'data/11 Where I\'m Trying To Go (Marvel Years Remix).mp3';

  request = new XMLHttpRequest();

  request.open('GET', url, true);

  request.responseType = "arraybuffer";

  request.onload = function() {
    return audio.decodeAudioData(request.response, function(buffer) {
      var analyser, myOscilloscope, source, sourceJs;
      source = audio.createBufferSource();
      source.buffer = buffer;
      sourceJs = audio.createScriptProcessor(2048, 1, 1);
      sourceJs.buffer = buffer;
      analyser = audio.createAnalyser();
      analyser.smoothingTimeConstant = 1;
      analyser.fftSize = 512;
      source.connect(analyser);
      analyser.connect(sourceJs);
      myOscilloscope = new WavyJones(audio, 'oscilloscope');
      analyser.connect(myOscilloscope);
      sourceJs.onaudioprocess = function(e) {
        var array;
        array = new Uint8Array(analyser.frequencyBinCount);
        return analyser.getByteFrequencyData(array);
      };
      source.start(0);
    });
  };

  request.send();

}).call(this);
